---
- name: cluster configured?
  stat:
    path: /etc/kubernetes/admin.conf
  register: cluster

- name: pull images
  shell: |
    kubeadm config images pull
  when: not cluster.stat.exists

- name: create cluster
  shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not cluster.stat.exists

- name: store join command
  shell: |
    kubeadm token create $(kubeadm token generate) --print-join-command --ttl=0 > /etc/kubernetes/join.info
  when: not cluster.stat.exists

- name: create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    remote_src: yes
  when: not cluster.stat.exists
